FROM fedora

RUN dnf -y update \
    && dnf -y install python3 ipython3 python3-pip python3-devel git \
    && dnf clean all

RUN pip3 install git+https://github.com/maffettone/bluesky-adaptive-ui.git@main#egg=bluesky-adaptive-ui
